// AIM build-out: final content for all 23 published rows, built entirely from real
// fetched content (aim.edu.au course pages, Industri Education's live-music-business page,
// AIM's global International English Language Requirements page) plus cited TEQSA/UAC
// evidence for archive and honest-null decisions. No invented text anywhere.
import fs from "node:fs";
import pg from "pg";

const ENGLISH_UG = "IELTS Academic 6.0 overall with no band less than 5.5 (AIM's own published International Entry Requirements page, Undergraduate tier; PTE Academic 50 with no skill below 42, TOEFL iBT overall 3.5 with Reading 3.5/Listening 3/Speaking 3/Writing 3, Cambridge C1 Advanced 169, CELPIP General 7, or LanguageCert Academic 65 with no component below 60 also accepted).";
const ENGLISH_PG = "IELTS Academic 6.5 overall with no band less than 6.0 (AIM's own published International Entry Requirements page, Postgraduate tier; PTE Academic 58 with no skill below 50, TOEFL iBT overall 4 with Reading 3.5/Listening 3.5/Speaking 3.5/Writing 4, Cambridge C1 Advanced 179, CELPIP General 8, or LanguageCert Academic 70 with no component below 65 also accepted).";

const results = [
  {
    id: "52fa4c80-a80b-41d4-a1da-50852691f494",
    name: "Bachelor of Music (Composition)",
    sourceUrl: "https://aim.edu.au/courses/bachelor-of-music-composition/",
    description: "The Bachelor of Music (Composition) is designed for composers who know they have something to say and are ready to learn how to say it at the highest level. Students develop the originality, technical mastery, and creative range to compose across film, television, video games, and digital media, exploring everything from orchestration and arranging to sound design and multimedia installation, guided by industry professionals who have scored, produced, and placed music at the highest levels of the industry. Delivered face to face with some online components at AIM's Melbourne and Sydney campuses; domestic students complete 6 study periods (2 years full-time) and international students 9 study periods (3 years full-time). TEQSA course CRS1401311, CRICOS 111590E.",
    curriculum: "Study Period 1: Composition Major 1, Music Specialisation Elective, Introduction to Higher Education Studies, Music Materials 1. Study Period 2: Composition Major 2, Collaboration Project 1, Art Meets Commerce (Arts and Entertainment Industry overview), Music Materials 2. Study Period 3: Composition Major 3, Collaboration Project 2, a Musicology scholarship unit (choice), Music Specialisation Elective. Study Period 4: Composition Major 4, Music Specialisation Elective, Musicology scholarship unit, Music Specialisation Elective. Study Period 5: Composition Major 5, Collaboration Project 3, Musicology scholarship unit, Music Specialisation Elective. Study Period 6 (Capstone): Bachelor of Music Capstone Project, Collaboration Project 4, Music Specialisation Elective. Musicology scholarship electives span Western Art Music, Popular Music, Music Theatre, Electronic Music, Screen Music, Australian Music, Game Music, Improvised Music, Jazz, Music Pedagogy and Music and Globalisation; Music Specialisation electives span Arts Management, Composition, Creative Technology, Performance and Acting (Sydney only) modules.",
    admission: "Domestic: completed Australian Year 12 (or overseas equivalent, including IB) within the last 2 years, or entry via tertiary study/mature-age pathway; applicants must attend an interview or live audition and provide a portfolio of two contrasting pieces. International: completed Australian Year 12 (or overseas equivalent, including IB) within the last 2 years, plus minimum standard English requirements; applicants must attend an interview and provide a portfolio of two contrasting pieces (AIM's own course page and Entry Requirements for International Students page).",
    english: ENGLISH_UG,
  },
  {
    id: "34899b8e-ca82-4e56-8d34-c936afab3fda",
    name: "Bachelor of Music (Creative Technology)",
    sourceUrl: "https://aim.edu.au/courses/bachelor-of-music-creative-technology/",
    description: "The Bachelor of Music (Creative Technology) covers what other institutions call audio engineering or music production, but AIM frames it as using technology as a creative instrument, combining proven theory with hands-on experience across recording, sound design, mixing, mastering and music technology. Delivered face to face with some online components at AIM's Melbourne and Sydney campuses; domestic students complete 6 study periods (2 years full-time) and international students 9 study periods (3 years full-time). TEQSA course CRS1401309, CRICOS 111579M.",
    curriculum: "Study Period 1: Creative Technology Major 1 (Capturing and Creating Sound), Music Specialisation Elective, Introduction to Higher Education Studies, Music Materials 1. Study Period 2: Creative Technology Major 2 (The Production Process), Collaboration Project 1, Art Meets Commerce, Music Materials 2. Study Period 3: Creative Technology Major 3 (Delivering Audio), Collaboration Project 2, a Musicology scholarship unit. Study Period 4: Creative Technology Major 4 (Sound in Other Media), Music Specialisation Elective, Musicology scholarship unit. Study Period 5: Creative Technology Major 5 (System Design), Collaboration Project 3, Musicology scholarship unit. Study Period 6 (Capstone): Bachelor of Music Capstone Project, Collaboration Project 4. Electives are shared across AIM's Bachelor of Music family, spanning Arts Management, Composition, Creative Technology, Performance, Acting (Sydney only) modules and the 11 Musicology scholarship units.",
    admission: "Domestic: completed Australian Year 12 (or overseas equivalent, including IB) within the last 2 years, or entry via tertiary study/mature-age pathway; applicants must attend an interview and provide a portfolio of two contrasting pieces. International: same academic requirement plus minimum standard English requirements; applicants must attend an interview and provide a portfolio of two contrasting pieces (AIM's own course page and Entry Requirements for International Students page).",
    english: ENGLISH_UG,
  },
  {
    id: "e28e54b8-fbe3-48ea-a544-0567ab41bd76",
    name: "Bachelor of Music (Musicology)",
    sourceUrl: "https://aim.edu.au/courses/bachelor-of-music-musicology/",
    description: "The Bachelor of Music (Musicology) explores the history, theory, and cultural influences that have shaped music throughout every era and across every corner of the world, developing the research skills and critical thinking to analyse music not just as sound but as a reflection of how people live, believe and resist. Delivered face to face with some online components at AIM's Melbourne and Sydney campuses; domestic students complete 6 study periods (2 years full-time, or 9 study periods part-time equivalent) and international students 9 study periods (3 years full-time). TEQSA course CRS1401307, CRICOS 111577B. Note: AIM's own live Course Structure accordion for this specific page currently displays the same private-lesson \"Performance Major\" unit sequence used on the Bachelor of Music (Performance) page rather than a Musicology-specific major sequence, an apparent template/content carryover on AIM's site; the curriculum below is built from the parts of the same page that are unambiguously Musicology-specific (its shared foundation units, its 11 named Musicology scholarship electives, and its capstone/collaboration units), not the seemingly mismatched major-sequence block.",
    curriculum: "Shared foundation units (all Bachelor of Music streams): Introduction to Higher Education Studies, Music Materials 1 and 2, Art Meets Commerce (Arts and Entertainment Industry overview), four Collaboration Project units, and a final Bachelor of Music Capstone Project. Musicology-specific scholarship electives (a defining feature of this stream, chosen across the degree): Musicology 1 Western Art Music, Musicology 2 Popular Music, Musicology 3 Music Theatre, Musicology 4 Electronic Music, Musicology 5 Screen Music, Musicology 6 Australian Music, Musicology 7 Game Music, Musicology 8 Improvised Music, Musicology 9 Jazz, Musicology 10 Music Pedagogy, Musicology 11 Music and Globalisation, plus an independent Research Project unit. Students also choose Music Specialisation electives spanning Arts Management, Composition, Creative Technology, Performance and Acting (Sydney only) modules.",
    admission: "Domestic: completed Australian Year 12 (or overseas equivalent, including IB) within the last 2 years, or entry via tertiary study/mature-age pathway; applicants must attend an interview and provide a portfolio of two contrasting pieces. International: same academic requirement plus minimum standard English requirements; applicants must attend an interview and provide a portfolio of two contrasting pieces (AIM's own course page and Entry Requirements for International Students page).",
    english: ENGLISH_UG,
  },
  {
    id: "df9d61ae-67ef-4937-80ca-fe24a5ce61b2",
    name: "Bachelor of Music (Performance)",
    sourceUrl: "https://aim.edu.au/courses/bachelor-of-music-performance/",
    description: "The Bachelor of Music (Performance) is built around weekly one-on-one private lessons on the student's chosen instrument or voice, supported by a Performance Practice class of masterclasses, workshops and seminars, developing the technical mastery, artistic depth and collaborative instinct to stand out as a performer through ensemble work and real-world performance opportunities. Delivered face to face with some online components at AIM's Melbourne and Sydney campuses; domestic students complete 6 study periods (2 years full-time) and international students 9 study periods (3 years full-time). TEQSA course CRS1401305, CRICOS 111575D.",
    curriculum: "Study Period 1: Performance Major 1 (weekly 1:1 lessons plus Performance Practice and Aural Skills), two Music Specialisation electives, Introduction to Higher Education Studies. Study Period 2: Performance Major 2, Collaboration Project 1, Art Meets Commerce, Music Materials 2. Study Period 3: Performance Major 3 (building toward a public recital), Collaboration Project 2, a Musicology scholarship unit, elective. Study Period 4: Performance Major 4, two Music Specialisation electives, Musicology scholarship unit, elective. Study Period 5: Performance Major 5, Collaboration Project 3, Musicology scholarship unit, elective. Study Period 6 (Capstone): Capstone Project (live recital, portfolio, recording or multimedia presentation), Collaboration Project 4, elective. Electives are shared across AIM's Bachelor of Music family (Arts Management, Composition, Creative Technology, Performance and Acting modules, plus 11 Musicology scholarship units).",
    admission: "Domestic: completed Australian Year 12 (or overseas equivalent, including IB) within the last 2 years, or entry via tertiary study/mature-age pathway; applicants must attend an interview or live audition and provide a portfolio of two live or recorded music performances. International: same academic requirement plus minimum standard English requirements; applicants must attend an interview and provide a portfolio of two recorded music performances (AIM's own course page and Entry Requirements for International Students page).",
    english: ENGLISH_UG,
  },
  {
    id: "03113ef2-b55f-4125-9aed-d5519a09b2d3",
    name: "Bachelor of Music Theatre",
    sourceUrl: "https://aim.edu.au/courses/bachelor-of-music-theatre/",
    description: "The Bachelor of Music Theatre trains across four disciplines at once, singing, dancing, acting and creating, with one-on-one tuition in singing and acting rather than folding those into shared group classes. It is a 3-year (9 study period), February-intake-only degree for both domestic and international students, developing vocal power, dramatic depth and stage presence through specialist tuition, ensemble collaboration projects and public performance seasons. Delivered face to face with some online components at AIM's Melbourne and Sydney campuses. TEQSA course CRS1401315, CRICOS 111595M.",
    curriculum: "Study Period 1: Performance Module 1 and Acting Specialisation Module, Collaboration Project 1, Introduction to Higher Education Studies. Study Period 2: Collaboration Project 1 (continued), Art Meets Commerce, Music Materials 1. Study Period 3: Performance Module 2 and Acting Specialisation Module 2, Music Materials 2. Study Period 4: Performance Skills 1 (The Singing Actor 1), Book Musicals scholarship unit, Dance elective 1. Study Period 5: Performance Skills 2 (The Singing Actor 2), Collaboration Project 3 (public season rehearsal), Movement and Voice 1. Study Period 6: Performance Skills 3 (The Singing Actor 3), Dance 2. Study Period 7: Performance Skills 4 (The Singing Actor 4), Jukebox Musicals and Rock Opera scholarship unit, Dance 3. Study Period 8: Performance Skills 5 (The Singing Actor 5), Collaboration Project 4 (public season rehearsal), Movement and Voice 2. Study Period 9 (Capstone): Music Theatre Capstone Project, a collaborative ensemble public production of original and/or extant Music Theatre works.",
    admission: "Domestic: completed Australian Year 12 (or overseas equivalent, including IB) within the last 2 years, or entry via tertiary study/mature-age pathway; applicants must attend a live audition and provide a portfolio of two contrasting pieces. International: same academic requirement plus minimum standard English requirements; applicants must attend an interview and provide a portfolio of two contrasting pieces (AIM's own course page and Entry Requirements for International Students page).",
    english: ENGLISH_UG,
  },
  {
    id: "7169f404-a9a0-420b-89f0-9262abb6dc20",
    name: "Diploma of Music",
    sourceUrl: "https://aim.edu.au/courses/diploma-of-music/",
    description: "AIM's Diploma of Music covers the core musical and academic skills to hit the ground running, alongside the flexibility to explore areas beyond a student's main instrument or discipline. It stands alone as an industry-recognised qualification and also connects directly to the Bachelor of Music, with all completed Diploma units credited so students who continue pick up as second-year students. Delivered face to face with some online components at AIM's Melbourne and Sydney campuses; 3 study periods (1 year full-time) or part-time equivalent. TEQSA course CRS1401304, CRICOS 111594A.",
    curriculum: "Study Period 1: two Music Specialisation Modules, Introduction to Higher Education Studies, Music Materials 1. Study Period 2: Collaboration Project 1, Art Meets Commerce (Arts and Entertainment Industry overview), Music Materials 2. Study Period 3: two further Music Specialisation Modules, Collaboration Project 2. Specialisation electives are drawn from the same Music Specialisation Module bank shared across AIM's Bachelor of Music family (Arts Management, Composition, Creative Technology, Performance and Acting modules), plus the 11 Musicology scholarship units and a Research Project unit.",
    admission: "Domestic: completed Australian Year 12 (or overseas equivalent, including IB) within the last 2 years, or entry via tertiary study/mature-age pathway; applicants should provide a resume outlining previous musical study and/or practical music experience and achievements. International: same academic requirement plus minimum standard English requirements, with the same resume requirement (AIM's own course page and Entry Requirements for International Students page).",
    english: ENGLISH_UG,
  },
  {
    id: "614212b3-b22f-4c15-81d5-46c9c79d8f53",
    name: "Graduate Diploma of Music",
    sourceUrl: "https://aim.edu.au/courses/graduate-diploma-of-music/",
    description: "The Graduate Diploma of Music is designed for musicians ready to move beyond skill development into advanced, self-directed practice, sitting between the Master of Music and the undergraduate degrees as a shorter, contained postgraduate credential. It builds on undergraduate studies through sustained project work, advanced research, and engagement with complex musical and industry frameworks, and can be pursued standalone or as a pathway into the Master of Music. Domestic students only; delivered face to face with some online components at AIM's Melbourne and Sydney campuses over 4 study periods (52 weeks) full-time or part-time equivalent. CRICOS 113143A. AIM was ranked #1 in Australia for Quality of Student Experience in Postgraduate Courses (QILT Survey 2024).",
    curriculum: "Study Period 1: Introduction to Music Research, Major Study 1. Study Period 2: Research Project 1, an elective. Study Period 3: an elective, Major Study 2. Study Period 1 (following year): Extended Research Proposal, Major Study 3. Two elective units are completed across the degree, chosen from Graduate Music and Sound for Media, Graduate Special Project, Graduate Production, Graduate Australian Music, Graduate Teaching Techniques (Early or Adult Learners), or the Introduction to Arts and Entertainment Management / Cultural Policy / Funding and Financial Management / Marketing and Public Relations / Ethics and Governance / Copyright Law / Managing Innovation / Executive Leadership and Strategic Planning / Cultivating Creativity arts-management elective series.",
    admission: "Domestic only: applicants must hold a Bachelor's Degree and have relevant professional experience in the musical field, and must attend an interview or live audition and provide a portfolio of two contrasting items in their field of interest (AIM's own course page).",
    english: "This course is only available to domestic students; AIM's own course page publishes no international IELTS/PTE/TOEFL requirement for it.",
  },
  {
    id: "8a22f798-fb1a-46c1-ad8b-0144c2b5714b",
    name: "Master of Music",
    sourceUrl: "https://aim.edu.au/courses/master-of-music/",
    description: "The Master of Music (MMus) is built around a significant, self-directed creative project of the student's choosing, a festival, an album, a body of new compositions, a piece of research, or a business plan for reaching new markets, developed over two years with mentorship from working artists, producers and researchers rather than a fixed syllabus of set units. Study time is divided roughly 50% creative project, 30% research, and 20% electives (spanning Music and Sound for Media, Production, Teaching Techniques, Finance and Governance). Delivered face to face with some online components at AIM's Melbourne and Sydney campuses over 6 study periods (2 years full-time) or part-time equivalent. TEQSA course CRS1401465, CRICOS 113142B. AIM was ranked #1 in Australia for Quality of Student Experience in Postgraduate Courses (QILT Survey 2024).",
    curriculum: "Study Period 1: Introduction to Music Research, Major Study 1. Study Period 2: Research Project, Elective 1. Study Period 3: Elective 2, Major Study 2. Study Period 4: Extended Research Proposal, Major Study 3. Study Period 5: Research Project 3, Major Study 4. Study Period 6 (Capstone): Capstone Creative Project. Electives are drawn from the Music Specialisation Module bank (Arts Management, Composition, Creative Technology, Performance and Acting modules) shared across AIM's postgraduate and undergraduate courses.",
    admission: "Domestic and international: applicants are required to have a Bachelor's degree and relevant professional experience in the music industry, or, without a bachelor's degree, may be offered a place based on extensive professional experience; applicants must attend an interview or live audition (international: interview) and provide a portfolio of two contrasting items in their field of interest (AIM's own course page and Entry Requirements for International Students page).",
    english: ENGLISH_PG,
  },
  {
    id: "614378f2-8449-44e8-a359-8d64c509ff30",
    name: "Graduate Certificate in Music",
    sourceUrl: "https://aim.edu.au/courses/graduate-certificate-of-music/",
    description: "AIM's Graduate Certificate of Music (published on AIM's own site as \"Graduate Certificate of Music\") extends a student's existing skills through targeted research and project work in a chosen area of interest, usable as a standalone qualification to sharpen expertise or as a credited pathway into the Master of Music. Roughly 50% of study is hands-on project work, 30% research skills, and 20% electives. Domestic students only; delivered face to face with some online components at AIM's Melbourne and Sydney campuses over 2 study periods (26 weeks) full-time or part-time equivalent. CRICOS 113145K. AIM was ranked #1 in Australia for Quality of Student Experience in Postgraduate Courses (QILT Survey 2024).",
    curriculum: "Study Period 1: Introduction to Music Research, Major Study 1. Study Period 2: Research Project 1, an elective chosen from Music and Sound for Media, Australian Music, Teaching Techniques (Early or Adult Learners), Production, an Arts Management module, or a Special Project (e.g. competition preparation, masterclasses).",
    admission: "Domestic only: applicants are required to have a Bachelor's Degree and relevant musical professional practice experience, and must attend an interview or live audition and provide a portfolio of two contrasting items in their field of interest (AIM's own course page).",
    english: "This course is only available to domestic students; AIM's own course page publishes no international IELTS/PTE/TOEFL requirement for it.",
  },
  {
    id: "75f50d5a-4c84-4a1a-87e8-49033b758afd",
    name: "Bachelor of Music Business",
    sourceUrl: "https://aim.edu.au/courses/bachelor-of-music-business/",
    description: "The Bachelor of Music Business is built for the next generation of music industry leaders, the deal-makers, brand-builders and creative strategists who drive artists' careers from behind the scenes, developing expertise across marketing, intellectual property, contract law, entrepreneurship, event management and strategic business planning. Delivered face to face with some online components at AIM's Melbourne and Sydney campuses; domestic students complete 6 study periods (2 years full-time) and international students 9 study periods (3 years full-time). TEQSA course CRS1401244, CRICOS 118156M. Per TEQSA's national register this course is the current name of what was previously accredited as \"Bachelor of Arts and Entertainment Management\".",
    curriculum: "Study Period 1: Art Meets Commerce (Arts and Entertainment Industry overview), Collaboration Project: Music Publishing, Introduction to Higher Education Studies, Arts and Entertainment Law. Study Period 2: Marketing/Meaning and Finding Your Tribe(s), Collaboration Project: Artist and Talent Management, Media Communications and Publicity, Leadership/Management and Corporate Governance. Study Period 3: Innovation/Disruption and Conformity, Economics and Financial Management, Startups (Entrepreneurship and Business Strategy capstone unit), elective. Study Period 4: Live Performance and Production Management, Collaboration Project: Record Labels, Business Planning and Strategy (global perspective), elective. Study Period 5: The Data Economy (data and analytics), Collaboration Project: Event Management, The Politics of Art (cultural policy and arts funding), elective. Study Period 6 (Capstone): Capstone Project: Industry Placement, Research Project.",
    admission: "Domestic: school leavers attend an over-the-phone interview with a future student advisor and provide a 300 to 500 word personal statement on their interest in Music Business and any relevant experience; tertiary-study/mature-age pathways also available. International: same interview and personal statement requirement, plus minimum standard English requirements (AIM's own course page and Entry Requirements for International Students page, which also lists this interview/personal statement format for the Bachelor of Music Business specifically).",
    english: ENGLISH_UG,
  },
  {
    id: "a38d49c6-c12f-477f-b44e-4d517e79ac27",
    name: "Diploma of Music Business",
    sourceUrl: "https://aim.edu.au/courses/diploma-of-music-business/",
    description: "AIM's Diploma of Music Business teaches the foundations of arts and entertainment law, management and corporate governance, with the opportunity to collaborate on real projects exploring music publishing and artist management; graduates may continue into the Bachelor of Music Business for further study and an industry internship. Delivered face to face with some online components at AIM's Melbourne and Sydney campuses over 3 study periods (1 year full-time) or part-time equivalent. TEQSA course CRS1401246, CRICOS 118155A. Per TEQSA's national register this course is the current name of what was previously accredited as \"Diploma of Arts and Entertainment Management\", and TEQSA currently records it as accredited on a teach-out basis (existing enrolments only) alongside its associate-degree equivalent.",
    curriculum: "Core areas of study: foundations of arts and entertainment law; management and corporate governance; collaborative projects on music publishing and artist management. AIM's own course page cites this content as a condensed lead-in to the Bachelor of Music Business's Study Period 1 to 3 units (Art Meets Commerce, Arts and Entertainment Law, Collaboration Project: Music Publishing, Leadership/Management and Corporate Governance), which graduates continuing into the Bachelor pick up with credit.",
    admission: "Domestic: completed Australian Year 12 (or overseas equivalent, including IB) within the last 2 years, or entry via tertiary study/mature-age pathway; applicants must provide a resume outlining previous musical study and/or practical music experience and achievements. International: same academic requirement plus minimum standard English requirements, with the same resume requirement (AIM's own course page and Entry Requirements for International Students page).",
    english: ENGLISH_UG,
  },
  {
    id: "21c9885d-595e-436d-a3bd-418c66783690",
    name: "Associate Degree of Music Business",
    sourceUrl: "https://www.industrieducation.com.au/degree-courses/live-music-business",
    description: "AIM's Associate Degree of Music Business is delivered at AIM's Melbourne campus by AIM's education partner Industri Education, marketed on Industri's own site as \"Live Music Business\". It is a 2-year, in-person program (96 credit points, 18 units) covering event operations, marketing, artist management and promotions, with real-world placements and collaboration projects run alongside industry partners including Untitled Group, Mushroom Group, Arts Centre Melbourne, Marriner Group, JPJ Audio and MPH Australia; credits are fully transferable into an AIM Bachelor's degree with one further year of study. Course code CRS1401245. Per TEQSA's national register this qualification's most recent accreditation record (under the current name \"Associate Degree of Music Business\", formerly \"Associate Degree of Arts and Entertainment Management\") is recorded as accredited on a teach-out basis; Industri Education's own live marketing page nonetheless continues to advertise a February 2027 intake and active applications, so this entry reflects Industri's real, currently-published page rather than treating the TEQSA teach-out note alone as discontinuation.",
    curriculum: "Year 1, Trimester 1: Introduction to Higher Education Studies, Arts Meets Commerce (overview of the Arts and Entertainment Industry), Arts and Entertainment Law. Trimester 2: Introduction to Arts and Society, Collaboration Project (booking, promoting and producing a real gig), Leadership/Management and Corporate Governance. Trimester 3: Marketing, Meaning and Finding Your Tribe, Collaboration Project (a second live event). Year 2, Trimester 1: Economics and Financial Management, Innovation/Disruption and Conformity, Collaboration Project (PR campaign for a real music event). Trimester 2: Live Performance and Production Management, The Social Manager (Introduction to the Social Sciences), Music Industry Placement. Trimester 3: Startups (Entrepreneurship and Business Strategy), a final Collaboration Project and industry placement.",
    admission: "No previous music industry experience required. Entry pathways: satisfactory completion of an Australian Senior Secondary Year 12 Certificate (e.g. HSC or VCE) within the last 2 years with a minimum Band 3 in HSC English Standard (or equivalent); completion of an IB Diploma within the past 2 years; an AQF VET qualification (Certificate IV or above) or equivalent; at least six months of full-time tertiary study at AQF level 5 or higher; or mature-age entry (21 years or older) (Industri Education's own course page FAQ).",
    english: "Industri Education's own course page does not publish a separate IELTS/PTE/TOEFL table; its FAQ addresses academic entry pathways only (see admission_requirements) and directs prospective international applicants to contact AIM directly.",
  },
];

const archives = [
  { id: "7b350a70-fec6-41c7-a771-2063a807d029", name: "Bachelor of Arts and Entertainment Management", reason: "Superseded name, not a currently marketed course: TEQSA's national register lists the current live accreditation as \"Bachelor of Music Business (formerly Bachelor of Arts and Entertainment Management)\", renewal date 08/06/2029; aim.edu.au's own sitemap, course-search dropdown and 2026 course guide only ever list \"Bachelor of Music Business\" (built separately in this same sprint), with no live page anywhere under the old name." },
  { id: "4f9f77f5-70f7-4fa4-b070-a2592f62db51", name: "Bachelor of Entertainment Management", reason: "Distinct, separately-numbered TEQSA course from Bachelor of Music Business/Arts and Entertainment Management; TEQSA's national register shows \"Bachelor of Entertainment Management\" accreditation expired effective 31/12/2025, with no live aim.edu.au page, no UAC listing, and no entry in AIM's 2026 course guide or course-enquiry dropdown." },
  { id: "5b32b161-1539-47ca-9e99-bbba22d038c5", name: "Bachelor of Performance", reason: "Distinct, separately-numbered TEQSA course from Bachelor of Music (Performance) (built separately in this same sprint); TEQSA's national register shows \"Bachelor of Performance\" accreditation expired effective 07/08/2022, with no live aim.edu.au page, no UAC listing, and no entry in AIM's 2026 course guide or course-enquiry dropdown." },
  { id: "428d3e9b-9efc-4575-8eec-6776c1bf3a64", name: "Diploma of Arts and Entertainment Management", reason: "Superseded name, not a currently marketed course: TEQSA's national register lists the current live accreditation as \"Diploma of Music Business (formerly Diploma of Arts and Entertainment Management)\" (built separately in this same sprint under its current name); aim.edu.au's own sitemap and course-enquiry dropdown only ever list \"Diploma of Music Business\", with no live page anywhere under the old name." },
  { id: "db7f9308-21ff-4f2c-94c0-24b34720e969", name: "Graduate Certificate in Arts Management", reason: "TEQSA's national register lists \"Graduate Certificate in Arts Management\" (this exact name) with course status Inactive and provider notation \"Not renewed\"; no live aim.edu.au page, no CRICOS code, and no entry in AIM's 2026 course guide or course-enquiry dropdown." },
  { id: "19fc7db5-c248-48da-a65e-afca65e07457", name: "Graduate Diploma of Arts Management", reason: "TEQSA's national register lists \"Graduate Diploma of Arts Management\" (this exact name) with course status Inactive and provider notation \"Not renewed\"; no live aim.edu.au page, no CRICOS code, and no entry in AIM's 2026 course guide or course-enquiry dropdown." },
  { id: "7c06f189-1b86-42db-afe3-fcb1053e627a", name: "Master of Arts Management", reason: "TEQSA's national register lists \"Master of Arts Management\" (this exact name) with course status Inactive and provider notation \"Not renewed\"; no live aim.edu.au page, no CRICOS code, and no entry in AIM's 2026 course guide or course-enquiry dropdown." },
  { id: "0282f842-82c2-462a-8abc-9c43c2506134", name: "Master of Arts and Entertainment Management", reason: "Distinct TEQSA course from Master of Arts Management (also archived this sprint); TEQSA's national register shows \"Master of Arts and Entertainment Management\" accreditation expired effective 31/07/2026 (recently lapsed), with no live aim.edu.au page, no CRICOS code, and no entry in AIM's 2026 course guide or course-enquiry dropdown." },
  { id: "6a9497d9-9d6f-4c36-8aa2-d1168fe24eb4", name: "Foundation Program", reason: "No evidence this qualification has ever existed under AIM's provider registration: absent from TEQSA's full 44-entry national-register history for The Australian Institute of Music Limited (every course ever accredited to AIM, active or lapsed, under any name), absent from aim.edu.au's own site search, sitemap, 2026 course guide, course-enquiry dropdown, and UAC course listing, and no web search result ties a \"Foundation Program\" of any kind to AIM (aim.edu.au/life-at-aim/education-foundation/ is an unrelated philanthropic scholarship foundation, not an academic program)." },
];

const honestNulls = [
  { id: "286c9328-b7bf-47ab-bd60-bd4d00f0b9a1", name: "Associate Degree of Music (Performance)", reason: "Genuinely accredited but with zero live marketing presence found anywhere: TEQSA's national register lists \"Associate Degree of Music (Performance)\" as currently accredited, renewal date 27/10/2029 (not expired, not teach-out), yet it has no page on aim.edu.au (absent from the courses sitemap, course guide, course-search dropdown and WP site search), no UAC undergraduate listing (the UAC course-search filtered to AIM lists only 9 Bachelor/Diploma/Undergraduate-Certificate titles, no Associate Degrees), and Industri Education (AIM's Associate Degree delivery partner) markets only two Associate Degrees, Live Production and Live Music Business, neither of which is this course." },
  { id: "931adef6-877f-465f-9bb0-808f8b7515a5", name: "Associate Degree of Music Theatre", reason: "Genuinely accredited but with zero live marketing presence found anywhere: TEQSA's national register lists \"Associate Degree of Music Theatre\" as currently accredited, renewal date 27/10/2029 (not expired, not teach-out), yet it has no page on aim.edu.au (absent from the courses sitemap, course guide, course-search dropdown and WP site search), no UAC undergraduate listing, and Industri Education (AIM's Associate Degree delivery partner) markets only Live Production and Live Music Business, neither of which is this course." },
];

if (process.argv.includes("--dry")) {
  console.log("Build:", results.length, "Archive:", archives.length, "Honest null:", honestNulls.length, "Total:", results.length + archives.length + honestNulls.length);
  process.exit(0);
}

fs.writeFileSync("scripts/data/aim_final_content.json", JSON.stringify(results, null, 2));
fs.writeFileSync("scripts/data/aim_archive_list.json", JSON.stringify(archives, null, 2));
fs.writeFileSync("scripts/data/aim_honest_null_list.json", JSON.stringify(honestNulls, null, 2));

console.log("Wrote", results.length, "build rows,", archives.length, "archive rows,", honestNulls.length, "honest-null rows. Total:", results.length + archives.length + honestNulls.length);

if (process.argv.includes("--commit")) {
  const env = Object.fromEntries(
    fs.readFileSync(".env.local", "utf8").split("\n").filter((l) => l.includes("="))
      .map((l) => { const i = l.indexOf("="); return [l.slice(0, i), l.slice(i + 1)]; }),
  );
  const client = new pg.Client({ connectionString: env.DATABASE_URL });
  await client.connect();
  let updated = 0;
  for (const r of results) {
    await client.query(
      `UPDATE programs SET description=$1, curriculum=$2, admission_requirements=$3, english_requirements=$4, source_url=$5, application_url=$5, updated_at=now() WHERE id=$6`,
      [r.description, r.curriculum, r.admission, r.english, r.sourceUrl, r.id],
    );
    updated++;
  }
  console.log("Committed", updated, "rows to Postgres.");
  await client.end();
}
